# Generated by Django 3.1.5 on 2021-04-13 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_name', models.CharField(max_length=150)),
                ('File_Creation_time_stamp', models.DateTimeField(blank=True, null=True)),
                ('File_description', models.TextField(blank=True)),
                ('File_url', models.URLField(default=None)),
                ('File_size', models.CharField(max_length=150)),
                ('bucket_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBuckets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bucket_name', models.CharField(max_length=200)),
                ('Bucket_Creation_time_stamp', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
